### ISSUE TITLE
AcmAutoRefreshSelect calls refetch when the selection is Disable refresh

### ISSUE THREAD

**Issue by birsanv** [open-cluster-management/ui-components#313]
If I go from an active refresh status to Disable refresh, before disabling the refresh, the refetch function is called one last time
This is an issue since most of the time the Disable refresh is selected when something is wrong with the UI or when you want to preserve the current state.

Steps : 
- select refresh every 1min , or any other interval
- now select Disable refresh
- right away a refetch is called; then the refresh action is disabled
Refetch should not be called at all

**Comment by birsanv** [comment]
@RobDolares can we have this looked into for 2.3 ?

**Comment by KevinFCormier** [comment]
I think this was fixed somewhere along the way, and I also fixed the case where if you hide the window and return to it, it was refreshing when disabled. (See https://github.com/open-cluster-management/ui-components/commit/304abc1ce7f942ce045a787ac5da65701d233fa2)

Can you please check and close @birsanv? Thanks.

**Comment by birsanv** [comment]
I can still reproduce the issue with the final 2.3 build 2.3.0-DOWNSTREAM-2021-06-23-22-07-39

If I select Disable refresh, refresh is called one more time
If I switch between tabs I can see the refresh is called again

**Comment by KevinFCormier** [comment]
Problem was fixed in `ui-components` v0.166.0

`application-ui` only picked up a version with this fix on [June 28](https://github.com/open-cluster-management/application-ui/blame/029615d24334b6e7501fba6c2e4c33078b11745b/package.json)

**Comment by birsanv** [comment]
closing since this was fixed with the latest code although the fix is not available with the final ACM 2.3 image
